name: syncToGitee
on: 
  push:
    branches:
      - gh-pages
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: 'github/MichaelGmx'
          dst: 'gitee/michaelgmx'
          dst_key: ${{ secrets.ADPCOMP_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "vuepress"
          force_update: true
          debug: true